apiVersion: "cloud.google.com/v1alpha1"
kind: "Instance"
metadata:
  name: "example"
spec:
  projectID: <gcp-project-id>
  payload:
    zone: us-central1-a
    name: example
    description: test instance
    machineType: https://www.googleapis.com/compute/v1/projects/<gcp-project-id>/zones/us-central1-a/machineTypes/custom-2-4096
    disks:
      - type: PERSISTENT
        boot: true
        autoDelete: true
        initializeParams:
          diskName: example-root
          sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-7-wheezy-v20140606
    networkInterfaces:
      - network: https://www.googleapis.com/compute/v1/projects/<gcp-project-id>/global/networks/default