apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "gcp-operator.fullname" . }}
  labels:
    app: {{ include "gcp-operator.name" . }}
    chart: {{ include "gcp-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gcp-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "gcp-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - gcp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: {{ include "gcp-operator.fullname" . }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret/google.json
          volumeMounts:
            - name: google-credentials
              mountPath: /etc/secret/google.json
              subPath: google.json
      volumes:
        - name: google-credentials
          secret:
            secretName: {{ .Values.gcpSecret }}
      resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
