kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "gcp-operator.fullname" . }}
  labels:
    app: {{ include "gcp-operator.name" . }}
    chart: {{ include "gcp-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - cloud.google.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "gcp-operator.fullname" . }}
  labels:
    app: {{ include "gcp-operator.name" . }}
    chart: {{ include "gcp-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "gcp-operator.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "gcp-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
